#ifndef TANJA84DK_CRYPT_MACROS_H
#define TANJA84DK_CRYPT_MACROS_H
/*
#define TANJA84DK_NAMESPACE_OPEN(NAME) namespace NAME {
#define TANJA84DK_NAMESPACE_CLOSE(NAME) }

#define TANJA84DK_ANONYMOUS_NAMESPACE_OPEN namespace {
#define TANJA84DK_ANONYMOUS_NAMESPACE_CLOSE }
*/
#endif  // TANJA84DK_CRYPT_MACROS_H